services:
  find_my:
    image: ghcr.io/watsona4/find_my:latest
    build: .
    restart: unless-stopped
    volumes:
      - ~/.ssh:/ssh:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - config.env
